### ISSUE TITLE
Promocode FREE doesn´t give error when not entering card

### ISSUE THREAD

**Issue by adelamar** [javismiles/torch#11]
Device: Mobile Android, IPAD IOS, windows Edge
Issue: when upgrading from a basic plan to a yearly plan, applying a FREE promotional code does not give an error when card not entered.. The Apply button works but then when pressing FREE(1 YEAR) button there is a wheel constantly going on and does not stop. I need to kill the process and go back
Tt should give me an error saying.. your card info has not been entered.....

**Comment by javismiles** [comment]
hey, yo lo probe ahora y me funciona sin problemasssss, mmm, hay que investigar,
I tried it now with a new user and works all good,
you should not need to enter the card when using the promocode Free, i dont enter it and it workssss

**Comment by javismiles** [comment]
looks like we fixed this, I found the problem, closing for now, if we find another prob we open another one
