### ISSUE TITLE
Grid in Piano 2 and double sound on list

### ISSUE THREAD

**Issue by skylight22** [javismiles/torch#48]
Grid isn't showing the lowest bottom row of squares when from albums one picks Piano2(Classic) and also  there's the same sound repeated on the list Piano L (oriental) 4th one on the 'Music Instr. for Brainstorming'  list and also repeated once more at the bottom of that same list, right before the last one.

**Comment by skylight22** [comment]
**Soundstorm/Brainstorming Sounds Albums:**
1st Anonymous - loading circle never disappears
3rd Anonymous - doesn't show complete bottom grid/tight/mid row
5th Anonymous - doesn't show complete bottom grid/tight/mid row
6th Anonymous - doesn't show complete bottom grid/tight/mid row
7th Anonymous - doesn't show complete bottom grid/tight/mid row

**Music Instruments for Brainstorming:**
Piano2 (Classic) - doesn't show complete bottom grid/tight/mid row
Piano L (Oriental) - twice on the list, same sounds

**Comment by javismiles** [comment]
fixed
