### ISSUE TITLE
When trying to "join for free" username inputs are not valid (Android mobile)

### ISSUE THREAD

**Issue by adelamar** [javismiles/torch#6]
Device: Android mobile (using like native app from home screen)
Issue: when trying to join for free with a username Adela, the app gives an error "Some of your inputs are not valid" and doesn´t allow me to create an account.
It doesn´t happen in IOS ipad or Windows10 Edge

**Comment by javismiles** [comment]
This is weird, I have joined 100 times from android  myself without issues, lets investigate

**Comment by javismiles** [comment]
the problem is that I dont allow uppercase, but I should explain this, I will add a comment that explains it when  you try it

**Comment by javismiles** [comment]
possibility, allow uppercase but then make it all lowercase later

**Comment by javismiles** [comment]
I have added a message that explains the user that only lowercase is allowed
