### ISSUE TITLE
Activation Link in verification email doesn´t take me to home app

### ISSUE THREAD

**Issue by adelamar** [javismiles/torch#8]
Device: Android Mobile Xperia phone
Issue: Torch app has been added to home screen.  When clicking on the activation link after registering, the link takes me to the Torch browser, not the Torch app in home screen. It should take me to home app if I have already added it to home app.

**Comment by javismiles** [comment]
This is normal behaviour. A url link from an email will always open a browser. We cannot change this, it happens by tech design of technology creators. I agree with you that it could be better, but nowadays urls on emails always open browsers. Problem is I dont think there is any way to from an email to the home app, if its a web progressive app, good point anyway

**Comment by javismiles** [comment]
a possible way to investigate
https://developer.android.com/guide/appendix/g-app-intents.html

**Comment by javismiles** [comment]
Researched and didnt find a way yet, postponed
